### ISSUE TITLE
How to protect the root api with loopback-gateway ?

### ISSUE THREAD

**Issue by zetflo** [strongloop/loopback-gateway#15]
Hello,
I recovered and tested the example, everything works perfectly . 
However, I can not protect the root api with _internal in the example or /api on a typical project. 
Is this possible ? how should it proceed?

For example
oauth2.authenticate ( [' / api '] , { session : false , scope: 'demo' });

does not work when I call https:// localhost:3001/api/applications

Thank you in advance for your return.

**Comment by raymondfeng** [comment]
Where did you put `oauth2.authenticate ( [' / api '] , { session : false , scope: 'demo' });`? The middleware should come before `loopback.rest`.

BTW, the latest version of loopback-gateway already registers middleware by phases for ordering. See http://docs.strongloop.com/display/LB/Defining+middleware

**Comment by zetflo** [comment]
Thanks for your replies, i have test this code in the boot sequence (rest-api.js) but without success. 

<pre>
module.exports = function mountRestApi(app) {

var oauth2 = require('loopback-component-oauth2').oAuth2Provider(
    app, {
        dataSource: app.dataSources.canope_api, // Data source for oAuth2 metadata persistence
        loginPage: '/login', // The login page url
        loginPath: '/login', // The login processing url
        userModel: app.loopback.getModelByType(app.models.Profil),
        applicationModel: app.loopback.getModelByType(app.models.application)
    });


    oauth2.authenticate(['/api'], {session: false, scope: 'demo'});

    var restApiRoot = app.get('restApiRoot');
  app.use(restApiRoot, app.loopback.rest());
};
</pre>

The root api is always accessible without oauth2 authentification.

**Comment by zetflo** [comment]
Your Commit 2816c889a8021fc5ac8621c4c3ac862764b7d02e solve my issue
Thanks
