### ISSUE TITLE
clientCredentials flow not working

### ISSUE THREAD

**Issue by JonnyBGod** [strongloop/loopback-gateway#16]
When using clientCredentials flow the token and refresh tokens are generated but when making a request it responds 401 'Unauthorized'. This happens in this project demo app and in my own implementation.

I believe this happens because the token is generated without a userId.

I am not sure how is it the best practices for this. If you indicate the right path I can provide a PR.

**Comment by raymondfeng** [comment]
Generally speaking, client credentials flow only generates access token for non-user-owned resources. In conjunction with JWT, it can be extended to allow user ids with pre-authorized scopes for the given client app.

**Comment by JonnyBGod** [comment]
Ok. But then what is the purpose of supporting client credentials while the current implementation of the Bearer authentications only works when it finds an applications and a user?

**Comment by zetflo** [comment]
+1
I am also interested in this feature. 
I need to authenticate an application with anonymous users.

**Comment by dentrifonov** [comment]
+1

**Comment by dentrifonov** [comment]
+1
It fixed in (2.0.0-beta5)[https://github.com/strongloop/loopback-component-oauth2/releases/tag/v2.0.0-beta5] version of loopback-component-oauth2.
@raymondfeng Thanks!
