### ISSUE TITLE
Enhance loopback-geteway to be production-ready open API platform 

### ISSUE THREAD

**Issue by XinV** [strongloop/loopback-gateway#24]
In order to open the loopback-based APs to partner developers and 3rd party developers, there are some missing functionalities that can make the loopback-geteway a better proxy/gateway to support 3rd party developers, such as API analytics and reporting, documentation, developer portal. Is there anything that can be released soon?

**Comment by raymondfeng** [comment]
@XinV Please email callback@strongloop.com
